### ISSUE TITLE
Trinity: dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gcc/lib/gcc/8/libgomp.1.dylib

### ISSUE THREAD

**Issue by jsoghigian** [brewsci/homebrew-bio#543]
I received the error dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gcc/lib/gcc/8/libgomp.1.dylib while attempting to run Trinity following installation with brew install trinity.

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I was trying to run a test of Trinity after installation with brew install trinity, using the following command:
```
Trinity --seqType fq --max_memory 2G \
              --left reads.left.fq.gz \
              --right reads.right.fq.gz \
              --SS_lib_type RF \
              --CPU 4
```
Input data comes from the sample data distributed through Trinity's github, but the error I report below is present on my own reads as well.  

Partial output is below - Trinity proceeded to this step without indication of an error.
```
-------------------------------------------
----------- Jellyfish  --------------------
-- (building a k-mer catalog from reads) --
-------------------------------------------

Done converting input files.CMD: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > left.fa.K25.stats
CMD: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > right.fa.K25.stats
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gcc/lib/gcc/8/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats
  Reason: image not found
bash: line 1: 57290 Abort trap: 6           /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25 --num_threads 2 > left.fa.K25.stats
Thread 3 terminated abnormally: Error, cmd: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > left.fa.K25.stats died with ret 34304 at /usr/local/Cellar/trinity/2.8.3/libexec/util/insilico_read_normalization.pl line 762.
Error, thread exited with error Error, cmd: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > left.fa.K25.stats died with ret 34304 at /usr/local/Cellar/trinity/2.8.3/libexec/util/insilico_read_normalization.pl line 762.

dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gcc/lib/gcc/8/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats
  Reason: image not found
bash: line 1: 57292 Abort trap: 6           /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25 --num_threads 2 > right.fa.K25.stats
Thread 4 terminated abnormally: Error, cmd: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > right.fa.K25.stats died with ret 34304 at /usr/local/Cellar/trinity/2.8.3/libexec/util/insilico_read_normalization.pl line 762.
Error, thread exited with error Error, cmd: /usr/local/Cellar/trinity/2.8.3/libexec/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > right.fa.K25.stats died with ret 34304 at /usr/local/Cellar/trinity/2.8.3/libexec/util/insilico_read_normalization.pl line 762.

Error, 2 threads errored out at /usr/local/Cellar/trinity/2.8.3/libexec/util/insilico_read_normalization.pl line 963.
Error, cmd: /usr/local/Cellar/trinity/2.8.3/libexec/util/insilico_read_normalization.pl --seqType fq --JM 2G  --max_cov 200 --min_cov 1 --CPU 4 --output /Users/phelix/trinityrnaseq-Trinity-v2.8.4/sample_data/test_Trinity_Assembly/trinity_out_dir/insilico_read_normalization   --max_pct_stdev 10000  --SS_lib_type RF  --left /Users/phelix/trinityrnaseq-Trinity-v2.8.4/sample_data/test_Trinity_Assembly/reads.left.fq.gz --right /Users/phelix/trinityrnaseq-Trinity-v2.8.4/sample_data/test_Trinity_Assembly/reads.right.fq.gz --pairs_together --PARALLEL_STATS   died with ret 512 at /usr/local/Cellar/trinity/2.8.3/libexec/Trinity line 2684.
	main::process_cmd('/usr/local/Cellar/trinity/2.8.3/libexec/util/insilico_read_no...') called at /usr/local/Cellar/trinity/2.8.3/libexec/Trinity line 3230
	main::normalize('/Users/phelix/trinityrnaseq-Trinity-v2.8.4/sample_data/test_T...', 200, 'ARRAY(0x7f8fce9b60a8)', 'ARRAY(0x7f8fce9b60f0)') called at /usr/local/Cellar/trinity/2.8.3/libexec/Trinity line 3177
	main::run_normalization(200, 'ARRAY(0x7f8fce9b60a8)', 'ARRAY(0x7f8fce9b60f0)') called at /usr/local/Cellar/trinity/2.8.3/libexec/Trinity line 1314

```

This is the brew gist-log:
https://gist.github.com/3942165ec1d99df085305bb35ca50a3f

**Comment by jsoghigian** [comment]
Hi @sjackman , unfortunately this bug has re-appeared after updating Trinity via homebrew.  Same error as above (I can give a new paste if needed).

**Comment by sjackman** [comment]
Thanks for the bug report, and sorry for the hassle, @jsoghigian. Fixed by commit 169ff2f1699c9ed5b6d856fedee14ceabcfe5117.

@jonchang There's a bug where some formulae are being detected as `any_skip_relocation` rather than `any`. Be skeptical when a `revision` changes `cellar :any` to `cellar :any_skip_relocation`, especially when the formula has dependencies and definitely when it has dynamic linkage. Finding the root cause of this issue would be very helpful, if anyone wishes to volunteer.

**Comment by jsoghigian** [comment]
Thanks @sjackman , Trinity is working again following an update and reinstallation.

**Comment by sjackman** [comment]
Glad to hear it. Thanks for for following up.

**Comment by DDashevsky** [comment]
Hi @sjackman , I just ran into this exact same bug. I have previously run Trinity successfully on this machine, but it started giving me this error today. I have run `brew update` and `brew reinstall trinity` but the bug persists. The computer in question is an iMac running OS 10.12.6 if that helps.

Thanks,
DSD

**Comment by tseemann** [comment]
@DDashevsky I am not sure if homebrew supports 10.12 anymore?

**Comment by DDashevsky** [comment]
I upgraded to OS X 10.14, but now Trinity won't install at all. I'll open a new thread regarding that issue.
